# @name listar
GET http://localhost:4000/api/favoritos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

###

# @name query
GET http://localhost:4000/api/favoritos/consulta/?idArticulo=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

###

# @name porId
GET http://localhost:4000/api/favoritos/porId/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

###

# @name porUsuario
GET http://localhost:4000/api/favoritos/porUsuario
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

###

# @name agregar
POST http://localhost:4000/api/favoritos/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

###

# @name agregar
POST http://localhost:4000/api/favoritos/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

{
	"idArticulo": 1
}
###

# @name agregar
POST http://localhost:4000/api/favoritos/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

{
	"idArticulo": 2
}
###

# @name eliminar
DELETE http://localhost:4000/api/favoritos/delete/?idArticulo=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjcsImNvcnJlbyI6InV3dUB1d3UuY29tIiwiaWF0IjoxNjQ5NTQ1NTcyfQ.z7Qwc9_-gEkicc1L0O6oO_lg4W5jDT1lWZ1B21Dlpps 

###

