# @name loginUsuario
POST http://localhost:4000/api/login
Content-Type: application/json

{
	"correo": "uwu@uwu.com",
	"contraseña": "uwu",
	"esPublicador": false 
}
###

# @name loginUsuario2
POST https://edu-repo.azurewebsites.net/api/login
Content-Type: application/json

{
	"correo": "uwu@uwu.com",
	"contraseña": "uwu",
	"esPublicador": false 
}
###

# @name loginPublicador
POST http://localhost:4000/api/login
Content-Type: application/json

{
	"correo": "general@edurepo.com",
	"contraseña": "uwu",
	"esPublicador": true
}
###
