# @name listar
GET http://localhost:4000/api/materias
Content-Type: application/json
###

# @name agregar
POST http://localhost:4000/api/materias/add
Content-Type: application/json

{
	"nombre": "HP",
	"nivel": "Secundaria"
}
###

# @name agregar2
POST https://edu-repo.azurewebsites.net/api/materias/add
Content-Type: application/json

{
	"nombre": "Historia del Perú",
	"nivel": "Secundaria"
}
###

# @name delete
DELETE http://localhost:4000/api/materias/delete/4
Content-Type: application/json
###
