# @name listar
GET http://localhost:4000/api/materias
Content-Type: application/json
###

# @name agregar
POST http://localhost:4000/api/tags/add
Content-Type: application/json

{
	"idArticulo": 6,
	"nombre": "Secundaria"
}
###


