# @name listar
GET http://localhost:4000/api/usuarios
Content-Type: application/json
###
# @name listar2
GET https://edu-repo.azurewebsites.net/api/usuarios
Content-Type: application/json
###
# @name agregar
POST http://localhost:4000/api/usuarios/add
Content-Type: application/json

{
	"nombreUsuario": "asd",
	"contraseña": "owo",
	"nombres": "Estebana",
	"apellidos": "Carla",
	"edad": 21,
	"correo": "uwu@uwu.com"
}
###


